Repository IvyMic/guessVu, pull requests merged in 2018-11, with the labels that each got.

#2 User model
  frontend/src/App.test.js
  models/users.js
  package-lock.json
  package.json
  test/models/users.test.js
Labels: enhancement

#1 New world test
  app.test.js
  frontend/dist/js/main.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/chatroom.js
  frontend/src/form.js
  frontend/src/home.js
  package-lock.json
  package.json
Labels: enhancement

#4 Updated README.md
  .vscode/settings.json
  readme.md
Labels: enhancement

#6 quick change by Seb to fix merge conflict
  frontend/dist/js/main.js
  frontend/package.json
  frontend/src/chatroom.js
Labels: enhancement

#7 save message method doesnt take real name as a parameter
  app.js
  models/messages.js
Labels: Refactoring

#12 updated window title
  .gitignore
  frontend/dist/index.html
  frontend/public/index.html
Labels: enhancement

#14 Form component is now a stateless functional component
  frontend/src/form.js
Labels: Refactoring

#11 Socket testing
  app.test.js
  frontend/dist/js/main.js
  frontend/src/chatroom.js
  test/features/app.test.js
  test/features/socket.test.js
  test/models/messages.test.js
Labels: Refactoring

#10 fake name placeholder is displayed with message
  frontend/dist/js/main.js
  frontend/src/displayMessages.js
  models/messages.js
Labels: enhancement

#9 input value now resets once message is sent
  frontend/dist/js/main.js
  frontend/src/chatroom.js
Labels: enhancement

#13 Create user
  app.js
  frontend/dist/js/main.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/chatroom.js
  frontend/src/form.js
  frontend/src/home.js
  models/users.js
  package-lock.json
  package.json
  routes.js
  test/models/users.test.js
Labels: enhancement

#17 apply solving to user model
  models/users.js
  routes.js
  test/models/users.test.js
Labels: enhancement

#18 Display name taken
  frontend/dist/js/main.js
  frontend/src/alert.js
  frontend/src/form.js
  test/features/app.test.js
Labels: enhancement

#19 Real name cant be fake name
  models/users.js
  test/features/app.test.js
  test/models/users.test.js
Labels: enhancement

#23 Leavegame
  app.js
  frontend/dist/js/main.js
  frontend/src/chatroom.js
  frontend/src/leave.js
  models/messages.js
  models/users.js
  routes.js
  socket.js
  test/models/messages.test.js
  test/models/users.test.js
Labels: enhancement

#26 Update users on signup
  app.js
  frontend/dist/js/main.js
  frontend/src/App.js
  frontend/src/chatroom.js
  frontend/src/form.js
  frontend/src/leave.js
  frontend/src/startGame.js
  routes.js
  socket.js
Labels: enhancement

#28 Chatroom css
  frontend/dist/386adcc80542c36d7025aecd69e071db.png
  frontend/dist/4ee14d28fa6a0b1cd95ff044589d34ab.png
  frontend/dist/770847d18c73b438eb85ef0ca46c2319.svg
  frontend/dist/895a8fa710ca49730d6d58a5195290e1.png
  frontend/dist/index.html
  frontend/dist/js/main.js
  frontend/package-lock.json
  frontend/package.json
  frontend/public/index.html
  frontend/public/my-logo-fuschia.png
  frontend/public/my-logo-stark.png
  frontend/public/my-logo.png
  frontend/src/App.js
  frontend/src/chatroom.js
  frontend/src/displayMessages.js
  frontend/src/fakeNames.js
  frontend/src/form.js
  frontend/src/guess.js
  frontend/src/home.js
  frontend/src/leave.js
  frontend/src/realNames.js
  frontend/styles/app.css
  frontend/styles/buttons.css
  frontend/styles/chatroom.css
  frontend/styles/displayMessages.css
  frontend/styles/form.css
  frontend/styles/guess.css
  frontend/styles/home.css
  frontend/styles/leave.css
  frontend/styles/names.css
  frontend/webpack.config.js
  test/features/app.test.js
Labels: enhancement

#29 real and fake names are now randomly displayed
  models/users.js
Labels: enhancement

#31 Fix merge
  frontend/dist/js/main.js
  frontend/src/chatroom.js
  frontend/src/startGame.js
  frontend/styles/chatroom.css
Labels: bug

#32 msg anonymous while game has not started
  frontend/dist/js/main.js
  frontend/src/chatroom.js
Labels: enhancement

#33 tests check for ids not classes
  frontend/dist/js/main.js
  frontend/src/App.js
  frontend/src/alert.js
  frontend/src/chatroom.js
  frontend/src/fakeNames.js
  frontend/src/guess.js
  frontend/src/home.js
  frontend/src/leave.js
  frontend/src/realNames.js
  frontend/src/resultOfGuess.js
  frontend/src/startGame.js
  test/features/app.test.js
Labels: bug

#34 add discovered property to user on backend
  models/users.js
  test/models/users.test.js
Labels: enhancement

#35 emit message to all once a user is discovered
  app.js
  frontend/dist/js/main.js
  socket.js
Labels: enhancement

#36 Discover backend
  app.js
  models/users.js
  test/models/users.test.js
Labels: bug

#37 Winning backend
  frontend/dist/js/main.js
  frontend/src/form.js
  frontend/src/guess.js
  models/users.js
  routes.js
  socket.js
  test/models/users.test.js
Labels: enhancement

#38 User discovered frontend 2
  frontend/dist/js/main.js
  frontend/src/App.js
  frontend/src/chatroom.js
  frontend/src/discovered.js
  frontend/src/guess.js
  socket.js
Labels: enhancement

#40 make color of winning msg white
  frontend/dist/js/main.js
  frontend/src/chatroom.js
  frontend/src/discovered.js
  frontend/src/gameWon.js
  frontend/src/guess.js
  frontend/styles/gameWon.css
  socket.js
Labels: enhancement

#43 font color white by default
  frontend/styles/app.css
Labels: enhancement

#44 More than two
  frontend/dist/js/main.js
  frontend/src/App.js
  frontend/src/alert.js
  frontend/src/chatroom.js
  frontend/styles/alert.css
  socket.js
Labels: enhancement

#45 fixed css when user has been discovered
  frontend/dist/js/main.js
  frontend/src/chatroom.js
  frontend/src/leave.js
  frontend/src/startGame.js
  frontend/styles/guess.css
  frontend/styles/leave.css
Labels: enhancement

#46 real and fake names are now displayed horizontally
  frontend/dist/js/main.js
  frontend/src/fakeNames.js
  frontend/src/realNames.js
  frontend/styles/names.css
Labels: enhancement

#47 Start new game
  frontend/dist/js/main.js
  frontend/src/chatroom.js
  frontend/src/startNewGame.js
  models/game.js
  routes.js
  socket.js
Labels: enhancement

#48 Max guesses
  frontend/dist/js/main.js
  frontend/src/App.js
  frontend/src/chatroom.js
  frontend/src/guess.js
  frontend/src/resultOfGuess.js
  frontend/styles/chatroom.css
  models/game.js
  models/users.js
  routes.js
  socket.js
  test/models/game.test.js
  test/models/users.test.js
Labels: enhancement

#49 fixed
  frontend/dist/js/main.js
  frontend/src/chatroom.js
  frontend/src/endGame.js
  models/game.js
  models/users.js
  routes.js
  socket.js
Labels: bug

#50 Fix guessing disappeared discover
  frontend/dist/js/main.js
  frontend/src/chatroom.js
  routes.js
  socket.js
Labels: bug

#53 page refreshes when game ends.
  frontend/dist/js/main.js
  frontend/src/chatroom.js
Labels: bug

#54 Not a winner when everyone else is knocked out fixed
  frontend/dist/js/main.js
  frontend/src/guess.js
  models/users.js
  package-lock.json
  routes.js
  test/models/users.test.js
Labels: bug

#57 displays err message if either fake or real names is empty
  frontend/dist/js/main.js
  frontend/src/form.js
Labels: bug

#55 now have selectors for names
  frontend/dist/js/main.js
  frontend/src/chatroom.js
  frontend/src/guess.js
Labels: enhancement

#56 fix for can't guess yourself
  frontend/dist/js/main.js
  routes.js
  test/models/users.test.js
Labels: bug

#62 fixed guess form css
  frontend/dist/js/main.js
  frontend/src/guess.js
  frontend/styles/app.css
  frontend/styles/chatroom.css
  frontend/styles/guess.css
Labels: enhancement

#59 number of players is displayed during the game
  frontend/dist/js/main.js
  frontend/src/chatroom.js
  frontend/src/guess.js
  frontend/styles/guess.css
  routes.js
  socket.js
Labels: enhancement

#60 start game btn disappears when you start game
  frontend/dist/js/main.js
  frontend/src/chatroom.js
Labels: enhancement

#61 Moved "You have been discovered" note to appear in place of guess component
  frontend/dist/js/main.js
  frontend/src/App.js
  frontend/src/chatroom.js
  frontend/src/discovered.js
  frontend/src/guess.js
  frontend/src/knockedOutMessage.js
  frontend/styles/gameWon.css
Labels: enhancement

#63 add winner method
  models/users.js
  routes.js
Labels: bug

#66 reduce font-size and margin
  frontend/dist/js/main.js
  frontend/src/chatroom.js
  frontend/src/fakeNames.js
  frontend/src/realNames.js
  frontend/src/showFakeNames.js
  frontend/src/showRealNames.js
  frontend/styles/chatroom.css
  frontend/styles/names.css
Labels: bug

#64 Changed name to show real name instead of fake name
  frontend/dist/js/main.js
  frontend/src/chatroom.js
Labels: enhancement

#65 hide the guessing form for winner when they win
  frontend/dist/js/main.js
  frontend/src/chatroom.js
Labels: enhancement

#67 added simple player number counter to pregame chatroom
  frontend/dist/js/main.js
  frontend/src/chatroom.js
Labels: enhancement

#68 all console.logs removed except those in frameworks
  frontend/dist/js/main.js
  frontend/src/App.js
  frontend/src/index.js
  models/game.js
Labels: enhancement
